(* Aesthetic Integration copyright 2018 *)
open Full_app_tags;;
open Yojson;;

let full_app_msg_tag_to_string (tag)  =
    (match tag with
        | Full_Msg_OrderSingle_Tag -> "OrderSingle"
        | Full_Msg_OrderCancelReplaceRequest_Tag -> "OrderCancelReplaceRequest"
        | Full_Msg_OrderCancelRequest_Tag -> "OrderCancelRequest"
        | Full_Msg_OrderMassCancelRequest_Tag -> "OrderMassCancelRequest"
        | Full_Msg_ExecutionReport_Tag -> "ExecutionReport"
        | Full_Msg_OrderCancelReject_Tag -> "OrderCancelReject"
        | Full_Msg_OrderMassCancelReport_Tag -> "OrderMassCancelReport"
    )
;;

let full_app_field_tag_to_string (tag)  =
    (match tag with
        | Full_Field_ClOrdID_Tag -> "ClOrdID"
        | Full_Field_ClientID_Tag -> "ClientID"
        | Full_Field_ExecBroker_Tag -> "ExecBroker"
        | Full_Field_Account_Tag -> "Account"
        | Full_Field_SettlmntTyp_Tag -> "SettlmntTyp"
        | Full_Field_FutSettDate_Tag -> "FutSettDate"
        | Full_Field_HandlInst_Tag -> "HandlInst"
        | Full_Field_ExecInst_Tag -> "ExecInst"
        | Full_Field_MinQty_Tag -> "MinQty"
        | Full_Field_MaxFloor_Tag -> "MaxFloor"
        | Full_Field_ExDestination_Tag -> "ExDestination"
        | Full_Field_ProcessCode_Tag -> "ProcessCode"
        | Full_Field_Symbol_Tag -> "Symbol"
        | Full_Field_SymbolSfx_Tag -> "SymbolSfx"
        | Full_Field_SecurityID_Tag -> "SecurityID"
        | Full_Field_IDSource_Tag -> "IDSource"
        | Full_Field_SecurityType_Tag -> "SecurityType"
        | Full_Field_MaturityMonthYear_Tag -> "MaturityMonthYear"
        | Full_Field_MaturityDay_Tag -> "MaturityDay"
        | Full_Field_PutOrCall_Tag -> "PutOrCall"
        | Full_Field_StrikePrice_Tag -> "StrikePrice"
        | Full_Field_OptAttribute_Tag -> "OptAttribute"
        | Full_Field_ContractMultiplier_Tag -> "ContractMultiplier"
        | Full_Field_CouponRate_Tag -> "CouponRate"
        | Full_Field_SecurityExchange_Tag -> "SecurityExchange"
        | Full_Field_Issuer_Tag -> "Issuer"
        | Full_Field_EncodedIssuerLen_Tag -> "EncodedIssuerLen"
        | Full_Field_EncodedIssuer_Tag -> "EncodedIssuer"
        | Full_Field_SecurityDesc_Tag -> "SecurityDesc"
        | Full_Field_EncodedSecurityDescLen_Tag -> "EncodedSecurityDescLen"
        | Full_Field_EncodedSecurityDesc_Tag -> "EncodedSecurityDesc"
        | Full_Field_PrevClosePx_Tag -> "PrevClosePx"
        | Full_Field_Side_Tag -> "Side"
        | Full_Field_LocateReqd_Tag -> "LocateReqd"
        | Full_Field_TransactTime_Tag -> "TransactTime"
        | Full_Field_OrderQty_Tag -> "OrderQty"
        | Full_Field_CashOrderQty_Tag -> "CashOrderQty"
        | Full_Field_OrdType_Tag -> "OrdType"
        | Full_Field_Price_Tag -> "Price"
        | Full_Field_StopPx_Tag -> "StopPx"
        | Full_Field_Currency_Tag -> "Currency"
        | Full_Field_ComplianceID_Tag -> "ComplianceID"
        | Full_Field_SolicitedFlag_Tag -> "SolicitedFlag"
        | Full_Field_IOIid_Tag -> "IOIid"
        | Full_Field_QuoteID_Tag -> "QuoteID"
        | Full_Field_TimeInForce_Tag -> "TimeInForce"
        | Full_Field_EffectiveTime_Tag -> "EffectiveTime"
        | Full_Field_ExpireDate_Tag -> "ExpireDate"
        | Full_Field_ExpireTime_Tag -> "ExpireTime"
        | Full_Field_GTBookingInst_Tag -> "GTBookingInst"
        | Full_Field_Commission_Tag -> "Commission"
        | Full_Field_CommType_Tag -> "CommType"
        | Full_Field_Rule80A_Tag -> "Rule80A"
        | Full_Field_ForexReq_Tag -> "ForexReq"
        | Full_Field_SettlCurrency_Tag -> "SettlCurrency"
        | Full_Field_Text_Tag -> "Text"
        | Full_Field_EncodedTextLen_Tag -> "EncodedTextLen"
        | Full_Field_EncodedText_Tag -> "EncodedText"
        | Full_Field_FutSettDate2_Tag -> "FutSettDate2"
        | Full_Field_OrderQty2_Tag -> "OrderQty2"
        | Full_Field_OpenClose_Tag -> "OpenClose"
        | Full_Field_CoveredOrUncovered_Tag -> "CoveredOrUncovered"
        | Full_Field_CustomerOrFirm_Tag -> "CustomerOrFirm"
        | Full_Field_MaxShow_Tag -> "MaxShow"
        | Full_Field_PegDifference_Tag -> "PegDifference"
        | Full_Field_DiscretionInst_Tag -> "DiscretionInst"
        | Full_Field_DiscretionOffset_Tag -> "DiscretionOffset"
        | Full_Field_ClearingFirm_Tag -> "ClearingFirm"
        | Full_Field_ClearingAccount_Tag -> "ClearingAccount"
        | Full_Field_TechnicalOrdType_Tag -> "TechnicalOrdType"
        | Full_Field_BookIndicator_Tag -> "BookIndicator"
        | Full_Field_MIC_Tag -> "MIC"
        | Full_Field_BrokerPrioritization_Tag -> "BrokerPrioritization"
        | Full_Field_DEAIndicator_Tag -> "DEAIndicator"
        | Full_Field_OrderAttributeTypes_Tag -> "OrderAttributeTypes"
        | Full_Field_NoAllocs_Tag -> "NoAllocs"
        | Full_Field_AllocAccount_Tag -> "AllocAccount"
        | Full_Field_AllocShares_Tag -> "AllocShares"
        | Full_Field_NoTradingSessions_Tag -> "NoTradingSessions"
        | Full_Field_TradingSessionID_Tag -> "TradingSessionID"
        | Full_Field_NoPartyIDs_Tag -> "NoPartyIDs"
        | Full_Field_PartyID_Tag -> "PartyID"
        | Full_Field_PartyIDSource_Tag -> "PartyIDSource"
        | Full_Field_PartyRole_Tag -> "PartyRole"
        | Full_Field_NoPartySubIDs_Tag -> "NoPartySubIDs"
        | Full_Field_PartySubID_Tag -> "PartySubID"
        | Full_Field_PartySubIDType_Tag -> "PartySubIDType"
        | Full_Field_NoClearingEntries_Tag -> "NoClearingEntries"
        | Full_Field_FreeText_Tag -> "FreeText"
        | Full_Field_ClearingHandlingType_Tag -> "ClearingHandlingType"
        | Full_Field_OrderID_Tag -> "OrderID"
        | Full_Field_OrigClOrdID_Tag -> "OrigClOrdID"
        | Full_Field_ListID_Tag -> "ListID"
        | Full_Field_SecondaryClOrdID_Tag -> "SecondaryClOrdID"
        | Full_Field_MassCancelRequestType_Tag -> "MassCancelRequestType"
        | Full_Field_TradingSessionSubID_Tag -> "TradingSessionSubID"
        | Full_Field_ClassID_Tag -> "ClassID"
        | Full_Field_CancelByLocationID_Tag -> "CancelByLocationID"
        | Full_Field_Product_Tag -> "Product"
        | Full_Field_CFICode_Tag -> "CFICode"
        | Full_Field_SecuritySubType_Tag -> "SecuritySubType"
        | Full_Field_MaturityDate_Tag -> "MaturityDate"
        | Full_Field_CouponPaymentDate_Tag -> "CouponPaymentDate"
        | Full_Field_IssueDate_Tag -> "IssueDate"
        | Full_Field_RepoCollateralSecurityType_Tag -> "RepoCollateralSecurityType"
        | Full_Field_RepurchaseTerm_Tag -> "RepurchaseTerm"
        | Full_Field_RepurchaseRate_Tag -> "RepurchaseRate"
        | Full_Field_Factor_Tag -> "Factor"
        | Full_Field_CreditRating_Tag -> "CreditRating"
        | Full_Field_InstrRegistry_Tag -> "InstrRegistry"
        | Full_Field_CountryOfIssue_Tag -> "CountryOfIssue"
        | Full_Field_StateOrProvinceOfIssue_Tag -> "StateOrProvinceOfIssue"
        | Full_Field_LocaleOfIssue_Tag -> "LocaleOfIssue"
        | Full_Field_RedemptionDate_Tag -> "RedemptionDate"
        | Full_Field_StrikeCurrency_Tag -> "StrikeCurrency"
        | Full_Field_Pool_Tag -> "Pool"
        | Full_Field_ContractSettlMonth_Tag -> "ContractSettlMonth"
        | Full_Field_CPProgram_Tag -> "CPProgram"
        | Full_Field_CPRegType_Tag -> "CPRegType"
        | Full_Field_DatedDate_Tag -> "DatedDate"
        | Full_Field_InterestAccrualDate_Tag -> "InterestAccrualDate"
        | Full_Field_NoSecurityAltID_Tag -> "NoSecurityAltID"
        | Full_Field_SecurityAltID_Tag -> "SecurityAltID"
        | Full_Field_SecurityAltIDSource_Tag -> "SecurityAltIDSource"
        | Full_Field_NoEvents_Tag -> "NoEvents"
        | Full_Field_EventType_Tag -> "EventType"
        | Full_Field_EventDate_Tag -> "EventDate"
        | Full_Field_EventPx_Tag -> "EventPx"
        | Full_Field_EventText_Tag -> "EventText"
        | Full_Field_UnderlyingSymbol_Tag -> "UnderlyingSymbol"
        | Full_Field_UnderlyingSymbolSfx_Tag -> "UnderlyingSymbolSfx"
        | Full_Field_UnderlyingSecurityID_Tag -> "UnderlyingSecurityID"
        | Full_Field_UnderlyingSecurityIDSource_Tag -> "UnderlyingSecurityIDSource"
        | Full_Field_UnderlyingProduct_Tag -> "UnderlyingProduct"
        | Full_Field_UnderlyingCFICode_Tag -> "UnderlyingCFICode"
        | Full_Field_UnderlyingSecurityType_Tag -> "UnderlyingSecurityType"
        | Full_Field_UnderlyingSecuritySubType_Tag -> "UnderlyingSecuritySubType"
        | Full_Field_UnderlyingMaturityMonthYear_Tag -> "UnderlyingMaturityMonthYear"
        | Full_Field_UnderlyingMaturityDate_Tag -> "UnderlyingMaturityDate"
        | Full_Field_UnderlyingCouponPaymentDate_Tag -> "UnderlyingCouponPaymentDate"
        | Full_Field_UnderlyingIssueDate_Tag -> "UnderlyingIssueDate"
        | Full_Field_UnderlyingRepoCollateralSecurityType_Tag -> "UnderlyingRepoCollateralSecurityType"
        | Full_Field_UnderlyingRepurchaseTerm_Tag -> "UnderlyingRepurchaseTerm"
        | Full_Field_UnderlyingRepurchaseRate_Tag -> "UnderlyingRepurchaseRate"
        | Full_Field_UnderlyingFactor_Tag -> "UnderlyingFactor"
        | Full_Field_UnderlyingCreditRating_Tag -> "UnderlyingCreditRating"
        | Full_Field_UnderlyingInstrRegistry_Tag -> "UnderlyingInstrRegistry"
        | Full_Field_UnderlyingCountryOfIssue_Tag -> "UnderlyingCountryOfIssue"
        | Full_Field_UnderlyingStateOrProvinceOfIssue_Tag -> "UnderlyingStateOrProvinceOfIssue"
        | Full_Field_UnderlyingLocaleOfIssue_Tag -> "UnderlyingLocaleOfIssue"
        | Full_Field_UnderlyingRedemptionDate_Tag -> "UnderlyingRedemptionDate"
        | Full_Field_UnderlyingStrikePrice_Tag -> "UnderlyingStrikePrice"
        | Full_Field_UnderlyingStrikeCurrency_Tag -> "UnderlyingStrikeCurrency"
        | Full_Field_UnderlyingOptAttribute_Tag -> "UnderlyingOptAttribute"
        | Full_Field_UnderlyingContractMultiplier_Tag -> "UnderlyingContractMultiplier"
        | Full_Field_UnderlyingCouponRate_Tag -> "UnderlyingCouponRate"
        | Full_Field_UnderlyingSecurityExchange_Tag -> "UnderlyingSecurityExchange"
        | Full_Field_UnderlyingIssuer_Tag -> "UnderlyingIssuer"
        | Full_Field_EncodedUnderlyingIssuerLen_Tag -> "EncodedUnderlyingIssuerLen"
        | Full_Field_EncodedUnderlyingIssuer_Tag -> "EncodedUnderlyingIssuer"
        | Full_Field_UnderlyingSecurityDesc_Tag -> "UnderlyingSecurityDesc"
        | Full_Field_EncodedUnderlyingSecurityDescLen_Tag -> "EncodedUnderlyingSecurityDescLen"
        | Full_Field_EncodedUnderlyingSecurityDesc_Tag -> "EncodedUnderlyingSecurityDesc"
        | Full_Field_UnderlyingCPProgram_Tag -> "UnderlyingCPProgram"
        | Full_Field_UnderlyingCPRegType_Tag -> "UnderlyingCPRegType"
        | Full_Field_UnderlyingCurrency_Tag -> "UnderlyingCurrency"
        | Full_Field_UnderlyingQty_Tag -> "UnderlyingQty"
        | Full_Field_UnderlyingPx_Tag -> "UnderlyingPx"
        | Full_Field_UnderlyingDirtyPrice_Tag -> "UnderlyingDirtyPrice"
        | Full_Field_UnderlyingEndPrice_Tag -> "UnderlyingEndPrice"
        | Full_Field_UnderlyingStartValue_Tag -> "UnderlyingStartValue"
        | Full_Field_UnderlyingCurrentValue_Tag -> "UnderlyingCurrentValue"
        | Full_Field_UnderlyingEndValue_Tag -> "UnderlyingEndValue"
        | Full_Field_NoUnderlyingSecurityAltID_Tag -> "NoUnderlyingSecurityAltID"
        | Full_Field_UnderlyingSecurityAltID_Tag -> "UnderlyingSecurityAltID"
        | Full_Field_UnderlyingSecurityAltIDSource_Tag -> "UnderlyingSecurityAltIDSource"
        | Full_Field_NoUnderlyingStips_Tag -> "NoUnderlyingStips"
        | Full_Field_UnderlyingStipType_Tag -> "UnderlyingStipType"
        | Full_Field_UnderlyingStipValue_Tag -> "UnderlyingStipValue"
        | Full_Field_SecondaryOrderID_Tag -> "SecondaryOrderID"
        | Full_Field_ExecID_Tag -> "ExecID"
        | Full_Field_ExecTransType_Tag -> "ExecTransType"
        | Full_Field_ExecRefID_Tag -> "ExecRefID"
        | Full_Field_ExecType_Tag -> "ExecType"
        | Full_Field_OrdStatus_Tag -> "OrdStatus"
        | Full_Field_OrdRejReason_Tag -> "OrdRejReason"
        | Full_Field_ExecRestatementReason_Tag -> "ExecRestatementReason"
        | Full_Field_LastShares_Tag -> "LastShares"
        | Full_Field_LastPx_Tag -> "LastPx"
        | Full_Field_LastSpotRate_Tag -> "LastSpotRate"
        | Full_Field_LastForwardPoints_Tag -> "LastForwardPoints"
        | Full_Field_LastMkt_Tag -> "LastMkt"
        | Full_Field_LastCapacity_Tag -> "LastCapacity"
        | Full_Field_LeavesQty_Tag -> "LeavesQty"
        | Full_Field_CumQty_Tag -> "CumQty"
        | Full_Field_AvgPx_Tag -> "AvgPx"
        | Full_Field_DayOrderQty_Tag -> "DayOrderQty"
        | Full_Field_DayCumQty_Tag -> "DayCumQty"
        | Full_Field_DayAvgPx_Tag -> "DayAvgPx"
        | Full_Field_TradeDate_Tag -> "TradeDate"
        | Full_Field_ReportToExch_Tag -> "ReportToExch"
        | Full_Field_GrossTradeAmt_Tag -> "GrossTradeAmt"
        | Full_Field_SettlCurrAmt_Tag -> "SettlCurrAmt"
        | Full_Field_SettlCurrFxRate_Tag -> "SettlCurrFxRate"
        | Full_Field_SettlCurrFxRateCalc_Tag -> "SettlCurrFxRateCalc"
        | Full_Field_MultiLegReportingType_Tag -> "MultiLegReportingType"
        | Full_Field_CrossType_Tag -> "CrossType"
        | Full_Field_UTPExID_Tag -> "UTPExID"
        | Full_Field_LiquidityIndicator_Tag -> "LiquidityIndicator"
        | Full_Field_ErrorCode_Tag -> "ErrorCode"
        | Full_Field_IMPTimestamp_Tag -> "IMPTimestamp"
        | Full_Field_NoContraBrokers_Tag -> "NoContraBrokers"
        | Full_Field_ContraBroker_Tag -> "ContraBroker"
        | Full_Field_ContraTrader_Tag -> "ContraTrader"
        | Full_Field_ContraTradeQty_Tag -> "ContraTradeQty"
        | Full_Field_ContraTradeTime_Tag -> "ContraTradeTime"
        | Full_Field_ContraLegRefID_Tag -> "ContraLegRefID"
        | Full_Field_CxlRejResponseTo_Tag -> "CxlRejResponseTo"
        | Full_Field_CxlRejReason_Tag -> "CxlRejReason"
        | Full_Field_MassCancelResponse_Tag -> "MassCancelResponse"
        | Full_Field_MassCancelRejectReason_Tag -> "MassCancelRejectReason"
        | Full_Field_TotalAffectedOrders_Tag -> "TotalAffectedOrders"
        | Full_Field_NoAffectedOrders_Tag -> "NoAffectedOrders"
        | Full_Field_AffectedOrderID_Tag -> "AffectedOrderID"
        | Full_Field_AffectedSecondaryOrderID_Tag -> "AffectedSecondaryOrderID"
    )
;;

let full_app_msg_tag_to_json (tag)  : json =
    `String (full_app_msg_tag_to_string tag)
;;

let full_app_msg_tag_opt_to_json (tag)  : json =
    (match tag with
        | None -> (`Null)
        | Some tag -> (full_app_msg_tag_to_json tag)
    )
;;

let full_app_field_tag_to_json (tag)  : json =
    `String (full_app_field_tag_to_string tag)
;;

let full_app_field_tag_opt_to_json (tag)  : json =
    (match tag with
        | None -> (`Null)
        | Some tag -> (full_app_field_tag_to_json tag)
    )
;;
