steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      docker build -t fix-engine-build . --target fix-engine-build
- name: 'gcr.io/cloud-builders/docker'
  id: 'run-tests'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      docker run --entrypoint /bin/bash fix-engine-build ./run_test.sh