# imandra-analyser-builder

FROM ocaml/opam:alpine-3.5_ocaml-4.02.3

# Wercker requires that we use the root user.
USER root
ENV OPAMROOT /home/opam/.opam

#Installing
RUN mkdir -p /app
WORKDIR /app
COPY ./Makefile /app/Makefile
RUN make dev-setup
