#!/bin/bash
rm -rf _site && docker build -t ai-gh-fix-engine . && docker run --user "$(id -u):$(id -g)" --rm -p 4000:4000  -v `pwd`:/srv/jekyll ai-gh-fix-engine bundle exec jekyll serve --host 0.0.0.0
