(* Aesthetic Integration copyright 2018 *)

type full_app_msg_tag =
    | Full_Msg_OrderSingle_Tag 
    | Full_Msg_OrderCancelReplaceRequest_Tag 
    | Full_Msg_OrderCancelRequest_Tag 
    | Full_Msg_OrderMassCancelRequest_Tag 
    | Full_Msg_ExecutionReport_Tag 
    | Full_Msg_OrderCancelReject_Tag 
    | Full_Msg_OrderMassCancelReport_Tag 
;;

type full_app_field_tag =
    | Full_Field_ClOrdID_Tag 
    | Full_Field_ClientID_Tag 
    | Full_Field_ExecBroker_Tag 
    | Full_Field_Account_Tag 
    | Full_Field_SettlmntTyp_Tag 
    | Full_Field_FutSettDate_Tag 
    | Full_Field_HandlInst_Tag 
    | Full_Field_ExecInst_Tag 
    | Full_Field_MinQty_Tag 
    | Full_Field_MaxFloor_Tag 
    | Full_Field_ExDestination_Tag 
    | Full_Field_ProcessCode_Tag 
    | Full_Field_Symbol_Tag 
    | Full_Field_SymbolSfx_Tag 
    | Full_Field_SecurityID_Tag 
    | Full_Field_IDSource_Tag 
    | Full_Field_SecurityType_Tag 
    | Full_Field_MaturityMonthYear_Tag 
    | Full_Field_MaturityDay_Tag 
    | Full_Field_PutOrCall_Tag 
    | Full_Field_StrikePrice_Tag 
    | Full_Field_OptAttribute_Tag 
    | Full_Field_ContractMultiplier_Tag 
    | Full_Field_CouponRate_Tag 
    | Full_Field_SecurityExchange_Tag 
    | Full_Field_Issuer_Tag 
    | Full_Field_EncodedIssuerLen_Tag 
    | Full_Field_EncodedIssuer_Tag 
    | Full_Field_SecurityDesc_Tag 
    | Full_Field_EncodedSecurityDescLen_Tag 
    | Full_Field_EncodedSecurityDesc_Tag 
    | Full_Field_PrevClosePx_Tag 
    | Full_Field_Side_Tag 
    | Full_Field_LocateReqd_Tag 
    | Full_Field_TransactTime_Tag 
    | Full_Field_OrderQty_Tag 
    | Full_Field_CashOrderQty_Tag 
    | Full_Field_OrdType_Tag 
    | Full_Field_Price_Tag 
    | Full_Field_StopPx_Tag 
    | Full_Field_Currency_Tag 
    | Full_Field_ComplianceID_Tag 
    | Full_Field_SolicitedFlag_Tag 
    | Full_Field_IOIid_Tag 
    | Full_Field_QuoteID_Tag 
    | Full_Field_TimeInForce_Tag 
    | Full_Field_EffectiveTime_Tag 
    | Full_Field_ExpireDate_Tag 
    | Full_Field_ExpireTime_Tag 
    | Full_Field_GTBookingInst_Tag 
    | Full_Field_Commission_Tag 
    | Full_Field_CommType_Tag 
    | Full_Field_Rule80A_Tag 
    | Full_Field_ForexReq_Tag 
    | Full_Field_SettlCurrency_Tag 
    | Full_Field_Text_Tag 
    | Full_Field_EncodedTextLen_Tag 
    | Full_Field_EncodedText_Tag 
    | Full_Field_FutSettDate2_Tag 
    | Full_Field_OrderQty2_Tag 
    | Full_Field_OpenClose_Tag 
    | Full_Field_CoveredOrUncovered_Tag 
    | Full_Field_CustomerOrFirm_Tag 
    | Full_Field_MaxShow_Tag 
    | Full_Field_PegDifference_Tag 
    | Full_Field_DiscretionInst_Tag 
    | Full_Field_DiscretionOffset_Tag 
    | Full_Field_ClearingFirm_Tag 
    | Full_Field_ClearingAccount_Tag 
    | Full_Field_TechnicalOrdType_Tag 
    | Full_Field_BookIndicator_Tag 
    | Full_Field_MIC_Tag 
    | Full_Field_BrokerPrioritization_Tag 
    | Full_Field_DEAIndicator_Tag 
    | Full_Field_OrderAttributeTypes_Tag 
    | Full_Field_NoAllocs_Tag 
    | Full_Field_AllocAccount_Tag 
    | Full_Field_AllocShares_Tag 
    | Full_Field_NoTradingSessions_Tag 
    | Full_Field_TradingSessionID_Tag 
    | Full_Field_NoPartyIDs_Tag 
    | Full_Field_PartyID_Tag 
    | Full_Field_PartyIDSource_Tag 
    | Full_Field_PartyRole_Tag 
    | Full_Field_NoPartySubIDs_Tag 
    | Full_Field_PartySubID_Tag 
    | Full_Field_PartySubIDType_Tag 
    | Full_Field_NoClearingEntries_Tag 
    | Full_Field_FreeText_Tag 
    | Full_Field_ClearingHandlingType_Tag 
    | Full_Field_OrderID_Tag 
    | Full_Field_OrigClOrdID_Tag 
    | Full_Field_ListID_Tag 
    | Full_Field_SecondaryClOrdID_Tag 
    | Full_Field_MassCancelRequestType_Tag 
    | Full_Field_TradingSessionSubID_Tag 
    | Full_Field_ClassID_Tag 
    | Full_Field_CancelByLocationID_Tag 
    | Full_Field_Product_Tag 
    | Full_Field_CFICode_Tag 
    | Full_Field_SecuritySubType_Tag 
    | Full_Field_MaturityDate_Tag 
    | Full_Field_CouponPaymentDate_Tag 
    | Full_Field_IssueDate_Tag 
    | Full_Field_RepoCollateralSecurityType_Tag 
    | Full_Field_RepurchaseTerm_Tag 
    | Full_Field_RepurchaseRate_Tag 
    | Full_Field_Factor_Tag 
    | Full_Field_CreditRating_Tag 
    | Full_Field_InstrRegistry_Tag 
    | Full_Field_CountryOfIssue_Tag 
    | Full_Field_StateOrProvinceOfIssue_Tag 
    | Full_Field_LocaleOfIssue_Tag 
    | Full_Field_RedemptionDate_Tag 
    | Full_Field_StrikeCurrency_Tag 
    | Full_Field_Pool_Tag 
    | Full_Field_ContractSettlMonth_Tag 
    | Full_Field_CPProgram_Tag 
    | Full_Field_CPRegType_Tag 
    | Full_Field_DatedDate_Tag 
    | Full_Field_InterestAccrualDate_Tag 
    | Full_Field_NoSecurityAltID_Tag 
    | Full_Field_SecurityAltID_Tag 
    | Full_Field_SecurityAltIDSource_Tag 
    | Full_Field_NoEvents_Tag 
    | Full_Field_EventType_Tag 
    | Full_Field_EventDate_Tag 
    | Full_Field_EventPx_Tag 
    | Full_Field_EventText_Tag 
    | Full_Field_UnderlyingSymbol_Tag 
    | Full_Field_UnderlyingSymbolSfx_Tag 
    | Full_Field_UnderlyingSecurityID_Tag 
    | Full_Field_UnderlyingSecurityIDSource_Tag 
    | Full_Field_UnderlyingProduct_Tag 
    | Full_Field_UnderlyingCFICode_Tag 
    | Full_Field_UnderlyingSecurityType_Tag 
    | Full_Field_UnderlyingSecuritySubType_Tag 
    | Full_Field_UnderlyingMaturityMonthYear_Tag 
    | Full_Field_UnderlyingMaturityDate_Tag 
    | Full_Field_UnderlyingCouponPaymentDate_Tag 
    | Full_Field_UnderlyingIssueDate_Tag 
    | Full_Field_UnderlyingRepoCollateralSecurityType_Tag 
    | Full_Field_UnderlyingRepurchaseTerm_Tag 
    | Full_Field_UnderlyingRepurchaseRate_Tag 
    | Full_Field_UnderlyingFactor_Tag 
    | Full_Field_UnderlyingCreditRating_Tag 
    | Full_Field_UnderlyingInstrRegistry_Tag 
    | Full_Field_UnderlyingCountryOfIssue_Tag 
    | Full_Field_UnderlyingStateOrProvinceOfIssue_Tag 
    | Full_Field_UnderlyingLocaleOfIssue_Tag 
    | Full_Field_UnderlyingRedemptionDate_Tag 
    | Full_Field_UnderlyingStrikePrice_Tag 
    | Full_Field_UnderlyingStrikeCurrency_Tag 
    | Full_Field_UnderlyingOptAttribute_Tag 
    | Full_Field_UnderlyingContractMultiplier_Tag 
    | Full_Field_UnderlyingCouponRate_Tag 
    | Full_Field_UnderlyingSecurityExchange_Tag 
    | Full_Field_UnderlyingIssuer_Tag 
    | Full_Field_EncodedUnderlyingIssuerLen_Tag 
    | Full_Field_EncodedUnderlyingIssuer_Tag 
    | Full_Field_UnderlyingSecurityDesc_Tag 
    | Full_Field_EncodedUnderlyingSecurityDescLen_Tag 
    | Full_Field_EncodedUnderlyingSecurityDesc_Tag 
    | Full_Field_UnderlyingCPProgram_Tag 
    | Full_Field_UnderlyingCPRegType_Tag 
    | Full_Field_UnderlyingCurrency_Tag 
    | Full_Field_UnderlyingQty_Tag 
    | Full_Field_UnderlyingPx_Tag 
    | Full_Field_UnderlyingDirtyPrice_Tag 
    | Full_Field_UnderlyingEndPrice_Tag 
    | Full_Field_UnderlyingStartValue_Tag 
    | Full_Field_UnderlyingCurrentValue_Tag 
    | Full_Field_UnderlyingEndValue_Tag 
    | Full_Field_NoUnderlyingSecurityAltID_Tag 
    | Full_Field_UnderlyingSecurityAltID_Tag 
    | Full_Field_UnderlyingSecurityAltIDSource_Tag 
    | Full_Field_NoUnderlyingStips_Tag 
    | Full_Field_UnderlyingStipType_Tag 
    | Full_Field_UnderlyingStipValue_Tag 
    | Full_Field_SecondaryOrderID_Tag 
    | Full_Field_ExecID_Tag 
    | Full_Field_ExecTransType_Tag 
    | Full_Field_ExecRefID_Tag 
    | Full_Field_ExecType_Tag 
    | Full_Field_OrdStatus_Tag 
    | Full_Field_OrdRejReason_Tag 
    | Full_Field_ExecRestatementReason_Tag 
    | Full_Field_LastShares_Tag 
    | Full_Field_LastPx_Tag 
    | Full_Field_LastSpotRate_Tag 
    | Full_Field_LastForwardPoints_Tag 
    | Full_Field_LastMkt_Tag 
    | Full_Field_LastCapacity_Tag 
    | Full_Field_LeavesQty_Tag 
    | Full_Field_CumQty_Tag 
    | Full_Field_AvgPx_Tag 
    | Full_Field_DayOrderQty_Tag 
    | Full_Field_DayCumQty_Tag 
    | Full_Field_DayAvgPx_Tag 
    | Full_Field_TradeDate_Tag 
    | Full_Field_ReportToExch_Tag 
    | Full_Field_GrossTradeAmt_Tag 
    | Full_Field_SettlCurrAmt_Tag 
    | Full_Field_SettlCurrFxRate_Tag 
    | Full_Field_SettlCurrFxRateCalc_Tag 
    | Full_Field_MultiLegReportingType_Tag 
    | Full_Field_CrossType_Tag 
    | Full_Field_UTPExID_Tag 
    | Full_Field_LiquidityIndicator_Tag 
    | Full_Field_ErrorCode_Tag 
    | Full_Field_IMPTimestamp_Tag 
    | Full_Field_NoContraBrokers_Tag 
    | Full_Field_ContraBroker_Tag 
    | Full_Field_ContraTrader_Tag 
    | Full_Field_ContraTradeQty_Tag 
    | Full_Field_ContraTradeTime_Tag 
    | Full_Field_ContraLegRefID_Tag 
    | Full_Field_CxlRejResponseTo_Tag 
    | Full_Field_CxlRejReason_Tag 
    | Full_Field_MassCancelResponse_Tag 
    | Full_Field_MassCancelRejectReason_Tag 
    | Full_Field_TotalAffectedOrders_Tag 
    | Full_Field_NoAffectedOrders_Tag 
    | Full_Field_AffectedOrderID_Tag 
    | Full_Field_AffectedSecondaryOrderID_Tag 
;;
