(* Aesthetic Integration copyright 2017 *)

type full_app_msg_tag =
    | Full_Msg_Advertisement_Tag 
    | Full_Msg_Allocation_Tag 
    | Full_Msg_AllocationInstructionAck_Tag 
    | Full_Msg_BidRequest_Tag 
    | Full_Msg_BidResponse_Tag 
    | Full_Msg_DontKnowTrade_Tag 
    | Full_Msg_Email_Tag 
    | Full_Msg_ExecutionReport_Tag 
    | Full_Msg_IOI_Tag 
    | Full_Msg_ListCancelRequest_Tag 
    | Full_Msg_ListExecute_Tag 
    | Full_Msg_ListStatus_Tag 
    | Full_Msg_ListStatusRequest_Tag 
    | Full_Msg_ListStrikePrice_Tag 
    | Full_Msg_MarketDataIncrementalRefresh_Tag 
    | Full_Msg_MarketDataRequest_Tag 
    | Full_Msg_MarketDataRequestReject_Tag 
    | Full_Msg_MarketDataSnapshotFullRefresh_Tag 
    | Full_Msg_MassQuote_Tag 
    | Full_Msg_News_Tag 
    | Full_Msg_OrderCancelReject_Tag 
    | Full_Msg_OrderCancelReplaceRequest_Tag 
    | Full_Msg_OrderCancelRequest_Tag 
    | Full_Msg_OrderList_Tag 
    | Full_Msg_OrderSingle_Tag 
    | Full_Msg_OrderStatusRequest_Tag 
    | Full_Msg_Quote_Tag 
    | Full_Msg_QuoteAcknowledgement_Tag 
    | Full_Msg_QuoteCancel_Tag 
    | Full_Msg_QuoteRequest_Tag 
    | Full_Msg_QuoteStatusRequest_Tag 
    | Full_Msg_SecurityDefinition_Tag 
    | Full_Msg_SecurityDefinitionRequest_Tag 
    | Full_Msg_SecurityStatus_Tag 
    | Full_Msg_SecurityStatusRequest_Tag 
    | Full_Msg_SettlementInstructions_Tag 
    | Full_Msg_TradingSessionStatus_Tag 
    | Full_Msg_TradingSessionStatusRequest_Tag 
;;

type full_app_field_tag =
    | Full_Field_AdvId_Tag 
    | Full_Field_AdvTransType_Tag 
    | Full_Field_AdvRefID_Tag 
    | Full_Field_Symbol_Tag 
    | Full_Field_SymbolSfx_Tag 
    | Full_Field_SecurityID_Tag 
    | Full_Field_IDSource_Tag 
    | Full_Field_SecurityType_Tag 
    | Full_Field_MaturityMonthYear_Tag 
    | Full_Field_MaturityDay_Tag 
    | Full_Field_PutOrCall_Tag 
    | Full_Field_StrikePrice_Tag 
    | Full_Field_OptAttribute_Tag 
    | Full_Field_ContractMultiplier_Tag 
    | Full_Field_CouponRate_Tag 
    | Full_Field_SecurityExchange_Tag 
    | Full_Field_Issuer_Tag 
    | Full_Field_EncodedIssuerLen_Tag 
    | Full_Field_EncodedIssuer_Tag 
    | Full_Field_SecurityDesc_Tag 
    | Full_Field_EncodedSecurityDescLen_Tag 
    | Full_Field_EncodedSecurityDesc_Tag 
    | Full_Field_AdvSide_Tag 
    | Full_Field_Shares_Tag 
    | Full_Field_Price_Tag 
    | Full_Field_Currency_Tag 
    | Full_Field_TradeDate_Tag 
    | Full_Field_TransactTime_Tag 
    | Full_Field_Text_Tag 
    | Full_Field_EncodedTextLen_Tag 
    | Full_Field_EncodedText_Tag 
    | Full_Field_URLLink_Tag 
    | Full_Field_LastMkt_Tag 
    | Full_Field_TradingSessionID_Tag 
    | Full_Field_AllocID_Tag 
    | Full_Field_AllocTransType_Tag 
    | Full_Field_RefAllocID_Tag 
    | Full_Field_AllocLinkID_Tag 
    | Full_Field_AllocLinkType_Tag 
    | Full_Field_Side_Tag 
    | Full_Field_AvgPx_Tag 
    | Full_Field_AvgPrxPrecision_Tag 
    | Full_Field_SettlmntTyp_Tag 
    | Full_Field_FutSettDate_Tag 
    | Full_Field_GrossTradeAmt_Tag 
    | Full_Field_NetMoney_Tag 
    | Full_Field_OpenClose_Tag 
    | Full_Field_NumDaysInterest_Tag 
    | Full_Field_AccruedInterestRate_Tag 
    | Full_Field_NoOrders_Tag 
    | Full_Field_ClOrdID_Tag 
    | Full_Field_OrderID_Tag 
    | Full_Field_SecondaryOrderID_Tag 
    | Full_Field_ListID_Tag 
    | Full_Field_WaveNo_Tag 
    | Full_Field_NoExecs_Tag 
    | Full_Field_LastShares_Tag 
    | Full_Field_ExecID_Tag 
    | Full_Field_LastPx_Tag 
    | Full_Field_LastCapacity_Tag 
    | Full_Field_NoAllocs_Tag 
    | Full_Field_AllocAccount_Tag 
    | Full_Field_AllocPrice_Tag 
    | Full_Field_AllocShares_Tag 
    | Full_Field_ProcessCode_Tag 
    | Full_Field_BrokerOfCredit_Tag 
    | Full_Field_NotifyBrokerOfCredit_Tag 
    | Full_Field_AllocHandlInst_Tag 
    | Full_Field_AllocText_Tag 
    | Full_Field_EncodedAllocTextLen_Tag 
    | Full_Field_EncodedAllocText_Tag 
    | Full_Field_ExecBroker_Tag 
    | Full_Field_ClientID_Tag 
    | Full_Field_Commission_Tag 
    | Full_Field_CommType_Tag 
    | Full_Field_AllocAvgPx_Tag 
    | Full_Field_AllocNetMoney_Tag 
    | Full_Field_SettlCurrAmt_Tag 
    | Full_Field_SettlCurrency_Tag 
    | Full_Field_SettlCurrFxRate_Tag 
    | Full_Field_SettlCurrFxRateCalc_Tag 
    | Full_Field_AccruedInterestAmt_Tag 
    | Full_Field_SettlInstMode_Tag 
    | Full_Field_NoMiscFees_Tag 
    | Full_Field_MiscFeeAmt_Tag 
    | Full_Field_MiscFeeCurr_Tag 
    | Full_Field_MiscFeeType_Tag 
    | Full_Field_AllocStatus_Tag 
    | Full_Field_AllocRejCode_Tag 
    | Full_Field_BidID_Tag 
    | Full_Field_ClientBidID_Tag 
    | Full_Field_BidRequestTransType_Tag 
    | Full_Field_ListName_Tag 
    | Full_Field_TotalNumSecurities_Tag 
    | Full_Field_BidType_Tag 
    | Full_Field_NumTickets_Tag 
    | Full_Field_SideValue1_Tag 
    | Full_Field_SideValue2_Tag 
    | Full_Field_LiquidityIndType_Tag 
    | Full_Field_WtAverageLiquidity_Tag 
    | Full_Field_ExchangeForPhysical_Tag 
    | Full_Field_OutMainCntryUIndex_Tag 
    | Full_Field_CrossPercent_Tag 
    | Full_Field_ProgRptReqs_Tag 
    | Full_Field_ProgPeriodInterval_Tag 
    | Full_Field_IncTaxInd_Tag 
    | Full_Field_ForexReq_Tag 
    | Full_Field_NumBidders_Tag 
    | Full_Field_TradeType_Tag 
    | Full_Field_BasisPxType_Tag 
    | Full_Field_StrikeTime_Tag 
    | Full_Field_NoBidDescriptors_Tag 
    | Full_Field_BidDescriptorType_Tag 
    | Full_Field_BidDescriptor_Tag 
    | Full_Field_SideValueInd_Tag 
    | Full_Field_LiquidityValue_Tag 
    | Full_Field_LiquidityNumSecurities_Tag 
    | Full_Field_LiquidityPctLow_Tag 
    | Full_Field_LiquidityPctHigh_Tag 
    | Full_Field_EFPTrackingError_Tag 
    | Full_Field_FairValue_Tag 
    | Full_Field_OutsideIndexPct_Tag 
    | Full_Field_ValueOfFutures_Tag 
    | Full_Field_NoBidComponents_Tag 
    | Full_Field_NetGrossInd_Tag 
    | Full_Field_Account_Tag 
    | Full_Field_Country_Tag 
    | Full_Field_PriceType_Tag 
    | Full_Field_DKReason_Tag 
    | Full_Field_OrderQty_Tag 
    | Full_Field_CashOrderQty_Tag 
    | Full_Field_EmailThreadID_Tag 
    | Full_Field_EmailType_Tag 
    | Full_Field_OrigTime_Tag 
    | Full_Field_Subject_Tag 
    | Full_Field_EncodedSubjectLen_Tag 
    | Full_Field_EncodedSubject_Tag 
    | Full_Field_RawDataLength_Tag 
    | Full_Field_RawData_Tag 
    | Full_Field_NoRoutingIDs_Tag 
    | Full_Field_RoutingType_Tag 
    | Full_Field_RoutingID_Tag 
    | Full_Field_NoRelatedSym_Tag 
    | Full_Field_RelatdSym_Tag 
    | Full_Field_LinesOfText_Tag 
    | Full_Field_OrigClOrdID_Tag 
    | Full_Field_ExecTransType_Tag 
    | Full_Field_ExecRefID_Tag 
    | Full_Field_ExecType_Tag 
    | Full_Field_OrdStatus_Tag 
    | Full_Field_OrdRejReason_Tag 
    | Full_Field_ExecRestatementReason_Tag 
    | Full_Field_OrdType_Tag 
    | Full_Field_StopPx_Tag 
    | Full_Field_PegDifference_Tag 
    | Full_Field_DiscretionInst_Tag 
    | Full_Field_DiscretionOffset_Tag 
    | Full_Field_ComplianceID_Tag 
    | Full_Field_SolicitedFlag_Tag 
    | Full_Field_TimeInForce_Tag 
    | Full_Field_EffectiveTime_Tag 
    | Full_Field_ExpireDate_Tag 
    | Full_Field_ExpireTime_Tag 
    | Full_Field_ExecInst_Tag 
    | Full_Field_Rule80A_Tag 
    | Full_Field_LastSpotRate_Tag 
    | Full_Field_LastForwardPoints_Tag 
    | Full_Field_LeavesQty_Tag 
    | Full_Field_CumQty_Tag 
    | Full_Field_DayOrderQty_Tag 
    | Full_Field_DayCumQty_Tag 
    | Full_Field_DayAvgPx_Tag 
    | Full_Field_GTBookingInst_Tag 
    | Full_Field_ReportToExch_Tag 
    | Full_Field_HandlInst_Tag 
    | Full_Field_MinQty_Tag 
    | Full_Field_MaxFloor_Tag 
    | Full_Field_MaxShow_Tag 
    | Full_Field_FutSettDate2_Tag 
    | Full_Field_OrderQty2_Tag 
    | Full_Field_ClearingFirm_Tag 
    | Full_Field_ClearingAccount_Tag 
    | Full_Field_MultiLegReportingType_Tag 
    | Full_Field_NoContraBrokers_Tag 
    | Full_Field_ContraBroker_Tag 
    | Full_Field_ContraTrader_Tag 
    | Full_Field_ContraTradeQty_Tag 
    | Full_Field_ContraTradeTime_Tag 
    | Full_Field_IOIid_Tag 
    | Full_Field_IOITransType_Tag 
    | Full_Field_IOIRefID_Tag 
    | Full_Field_IOIShares_Tag 
    | Full_Field_ValidUntilTime_Tag 
    | Full_Field_IOIQltyInd_Tag 
    | Full_Field_IOINaturalFlag_Tag 
    | Full_Field_SpreadToBenchmark_Tag 
    | Full_Field_Benchmark_Tag 
    | Full_Field_NoIOIQualifiers_Tag 
    | Full_Field_IOIQualifier_Tag 
    | Full_Field_ListStatusType_Tag 
    | Full_Field_NoRpts_Tag 
    | Full_Field_ListOrderStatus_Tag 
    | Full_Field_RptSeq_Tag 
    | Full_Field_ListStatusText_Tag 
    | Full_Field_EncodedListStatusTextLen_Tag 
    | Full_Field_EncodedListStatusText_Tag 
    | Full_Field_TotNoOrders_Tag 
    | Full_Field_CxlQty_Tag 
    | Full_Field_TotNoStrikes_Tag 
    | Full_Field_NoStrikes_Tag 
    | Full_Field_PrevClosePx_Tag 
    | Full_Field_MDReqID_Tag 
    | Full_Field_NoMDEntries_Tag 
    | Full_Field_MDUpdateAction_Tag 
    | Full_Field_DeleteReason_Tag 
    | Full_Field_MDEntryType_Tag 
    | Full_Field_MDEntryID_Tag 
    | Full_Field_MDEntryRefID_Tag 
    | Full_Field_FinancialStatus_Tag 
    | Full_Field_CorporateAction_Tag 
    | Full_Field_MDEntryPx_Tag 
    | Full_Field_MDEntrySize_Tag 
    | Full_Field_MDEntryDate_Tag 
    | Full_Field_MDEntryTime_Tag 
    | Full_Field_TickDirection_Tag 
    | Full_Field_MDMkt_Tag 
    | Full_Field_QuoteCondition_Tag 
    | Full_Field_TradeCondition_Tag 
    | Full_Field_MDEntryOriginator_Tag 
    | Full_Field_LocationID_Tag 
    | Full_Field_DeskID_Tag 
    | Full_Field_OpenCloseSettleFlag_Tag 
    | Full_Field_SellerDays_Tag 
    | Full_Field_QuoteEntryID_Tag 
    | Full_Field_MDEntryBuyer_Tag 
    | Full_Field_MDEntrySeller_Tag 
    | Full_Field_NumberOfOrders_Tag 
    | Full_Field_MDEntryPositionNo_Tag 
    | Full_Field_TotalVolumeTraded_Tag 
    | Full_Field_SubscriptionRequestType_Tag 
    | Full_Field_MarketDepth_Tag 
    | Full_Field_MDUpdateType_Tag 
    | Full_Field_AggregatedBook_Tag 
    | Full_Field_NoMDEntryTypes_Tag 
    | Full_Field_MDReqRejReason_Tag 
    | Full_Field_QuoteReqID_Tag 
    | Full_Field_QuoteID_Tag 
    | Full_Field_QuoteResponseLevel_Tag 
    | Full_Field_DefBidSize_Tag 
    | Full_Field_DefOfferSize_Tag 
    | Full_Field_NoQuoteSets_Tag 
    | Full_Field_QuoteSetID_Tag 
    | Full_Field_UnderlyingSymbol_Tag 
    | Full_Field_UnderlyingSymbolSfx_Tag 
    | Full_Field_UnderlyingSecurityID_Tag 
    | Full_Field_UnderlyingIDSource_Tag 
    | Full_Field_UnderlyingSecurityType_Tag 
    | Full_Field_UnderlyingMaturityMonthYear_Tag 
    | Full_Field_UnderlyingMaturityDay_Tag 
    | Full_Field_UnderlyingPutOrCall_Tag 
    | Full_Field_UnderlyingStrikePrice_Tag 
    | Full_Field_UnderlyingOptAttribute_Tag 
    | Full_Field_UnderlyingContractMultiplier_Tag 
    | Full_Field_UnderlyingCouponRate_Tag 
    | Full_Field_UnderlyingSecurityExchange_Tag 
    | Full_Field_UnderlyingIssuer_Tag 
    | Full_Field_EncodedUnderlyingIssuerLen_Tag 
    | Full_Field_EncodedUnderlyingIssuer_Tag 
    | Full_Field_UnderlyingSecurityDesc_Tag 
    | Full_Field_EncodedUnderlyingSecurityDescLen_Tag 
    | Full_Field_EncodedUnderlyingSecurityDesc_Tag 
    | Full_Field_QuoteSetValidUntilTime_Tag 
    | Full_Field_TotQuoteEntries_Tag 
    | Full_Field_NoQuoteEntries_Tag 
    | Full_Field_BidPx_Tag 
    | Full_Field_OfferPx_Tag 
    | Full_Field_BidSize_Tag 
    | Full_Field_OfferSize_Tag 
    | Full_Field_BidSpotRate_Tag 
    | Full_Field_OfferSpotRate_Tag 
    | Full_Field_BidForwardPoints_Tag 
    | Full_Field_OfferForwardPoints_Tag 
    | Full_Field_Urgency_Tag 
    | Full_Field_Headline_Tag 
    | Full_Field_EncodedHeadlineLen_Tag 
    | Full_Field_EncodedHeadline_Tag 
    | Full_Field_CxlRejResponseTo_Tag 
    | Full_Field_CxlRejReason_Tag 
    | Full_Field_ExDestination_Tag 
    | Full_Field_CoveredOrUncovered_Tag 
    | Full_Field_CustomerOrFirm_Tag 
    | Full_Field_LocateReqd_Tag 
    | Full_Field_NoTradingSessions_Tag 
    | Full_Field_ListExecInstType_Tag 
    | Full_Field_ListExecInst_Tag 
    | Full_Field_EncodedListExecInstLen_Tag 
    | Full_Field_EncodedListExecInst_Tag 
    | Full_Field_ListSeqNo_Tag 
    | Full_Field_QuoteAckStatus_Tag 
    | Full_Field_QuoteRejectReason_Tag 
    | Full_Field_QuoteEntryRejectReason_Tag 
    | Full_Field_QuoteCancelType_Tag 
    | Full_Field_QuoteRequestType_Tag 
    | Full_Field_SecurityReqID_Tag 
    | Full_Field_SecurityResponseID_Tag 
    | Full_Field_SecurityResponseType_Tag 
    | Full_Field_RatioQty_Tag 
    | Full_Field_UnderlyingCurrency_Tag 
    | Full_Field_SecurityRequestType_Tag 
    | Full_Field_SecurityStatusReqID_Tag 
    | Full_Field_UnsolicitedIndicator_Tag 
    | Full_Field_SecurityTradingStatus_Tag 
    | Full_Field_HaltReason_Tag 
    | Full_Field_InViewOfCommon_Tag 
    | Full_Field_DueToRelated_Tag 
    | Full_Field_BuyVolume_Tag 
    | Full_Field_SellVolume_Tag 
    | Full_Field_HighPx_Tag 
    | Full_Field_LowPx_Tag 
    | Full_Field_Adjustment_Tag 
    | Full_Field_SettlInstID_Tag 
    | Full_Field_SettlInstTransType_Tag 
    | Full_Field_SettlInstRefID_Tag 
    | Full_Field_SettlInstSource_Tag 
    | Full_Field_SettlLocation_Tag 
    | Full_Field_StandInstDbType_Tag 
    | Full_Field_StandInstDbName_Tag 
    | Full_Field_StandInstDbID_Tag 
    | Full_Field_SettlDeliveryType_Tag 
    | Full_Field_SettlDepositoryCode_Tag 
    | Full_Field_SettlBrkrCode_Tag 
    | Full_Field_SettlInstCode_Tag 
    | Full_Field_SecuritySettlAgentName_Tag 
    | Full_Field_SecuritySettlAgentCode_Tag 
    | Full_Field_SecuritySettlAgentAcctNum_Tag 
    | Full_Field_SecuritySettlAgentAcctName_Tag 
    | Full_Field_SecuritySettlAgentContactName_Tag 
    | Full_Field_SecuritySettlAgentContactPhone_Tag 
    | Full_Field_CashSettlAgentName_Tag 
    | Full_Field_CashSettlAgentCode_Tag 
    | Full_Field_CashSettlAgentAcctNum_Tag 
    | Full_Field_CashSettlAgentAcctName_Tag 
    | Full_Field_CashSettlAgentContactName_Tag 
    | Full_Field_CashSettlAgentContactPhone_Tag 
    | Full_Field_TradSesReqID_Tag 
    | Full_Field_TradSesMethod_Tag 
    | Full_Field_TradSesMode_Tag 
    | Full_Field_TradSesStatus_Tag 
    | Full_Field_TradSesStartTime_Tag 
    | Full_Field_TradSesOpenTime_Tag 
    | Full_Field_TradSesPreCloseTime_Tag 
    | Full_Field_TradSesCloseTime_Tag 
    | Full_Field_TradSesEndTime_Tag 
;;
